name: Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: New Push to Repository ${{ github.repository }}
        body: |
          Repository: ${{ github.repository }}
          Pusher: ${{ github.event.pusher.name }}
          Commit Message: ${{ github.event.head_commit.message }}

          ---
          heihei
        to: laurenparn@outlook.com
        from: Github actions

#ukskakskolm